SPOOL on;
ALTER SESSION SET container=xepdb1;

CREATE USER db1 IDENTIFIED BY db1 CONTAINER=CURRENT;

GRANT CONNECT TO db1 CONTAINER=CURRENT;
GRANT CREATE SESSION TO db1 CONTAINER=CURRENT;
GRANT RESOURCE TO db1 CONTAINER=CURRENT;

CREATE USER db2 IDENTIFIED BY db2 CONTAINER=CURRENT;

GRANT CONNECT TO db2 CONTAINER=CURRENT;
GRANT CREATE SESSION TO db2 CONTAINER=CURRENT;
GRANT RESOURCE TO db2 CONTAINER=CURRENT;

CREATE USER bughunter IDENTIFIED BY bughunter CONTAINER=CURRENT;
GRANT ALL PRIVILEGES TO bughunter CONTAINER=CURRENT;
